version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: carford
      POSTGRES_PASSWORD: carfordpass
      POSTGRES_DB: carforddb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    depends_on:
      - db

volumes:
  db_data:
